# -*- coding: utf-8 -*-
"""Unsloth-Haiku-Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ahYjTdXi5bgSNszGvcYej5qFUSVmmRvA
"""

# Commented out IPython magic to ensure Python compatibility.
# # Step 1: Install Dependencies
# 
# %%capture
# !pip install unsloth
# !pip install kaggle
# 
# !pip install trl
# 
# !pip install peft
# 
# !pip install torch
# 
# 
# 
# !pip install --upgrade tensorflow
# 
# !pip install --upgrade transformers
# 
# !pip install --upgrade transformers peft datasets accelerate
# 
#

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# # Skip restarting message in Colab
# import sys; modules = list(sys.modules.keys())
# for x in modules: sys.modules.pop(x) if "PIL" in x or "google" in x else None
# 
# !pip install unsloth vllm
# !pip install --upgrade pillow
# 
# !pip install git+https://github.com/huggingface/trl.git@e95f9fb74a3c3647b86f251b7e230ec51c64b72b

from unsloth import is_bfloat16_supported #type:ignore
import torch
from unsloth import FastLanguageModel
max_seq_length = 256 # Can increase for longer reasoning traces


model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "meta-llama/Llama-3.2-1B-Instruct",
    max_seq_length = max_seq_length,
    load_in_4bit = True, # False for LoRA 16bit
    fast_inference = True, # Enable vLLM fast inference
    #max_lora_rank = lora_rank, #type:ignore
    gpu_memory_utilization = 0.6, # Reduce if out of memory
    device_map="auto",
)

model = FastLanguageModel.get_peft_model(
    model,
    r = 8, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = [
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ], # Remove QKVO if out of memory
    lora_alpha = 8,
    use_gradient_checkpointing = "unsloth", # Enable long context finetuning
    random_state = 3407,
)

# Step 2: Upload the Kaggle Dataset Manually for google collaborate
from google.colab import files

# Upload the CSV file manually from your local system (unzip beforehand for convenience)
uploaded = files.upload()

import pandas as pd

# Load the CSV file, assuming the correct headers are in the second row (index 1)
df = pd.read_csv('/content/all_haiku.csv', header=0)

# Display the first few rows to confirm the columns are correct now (highly recommend kaggle datasets are unpredictable)
print(df.head())

# Check the first few rows of the dataframe to understand the structure
print(df.head())

# Step 5: Rename Columns and Remove Irrelevant Columns
# Manually rename the columns (based on the dataset structure)

df.rename(columns={
    '0': 'First Line',
    '1': 'Second Line',  # Renaming based on actual dataset
    '2': 'Third Line',  # Renaming based on actual dataset
}, inplace=True)

# Check the column names after renaming
print(df.columns)

# Remove any irrelevant columns (such as 'tempslibres' or 'FISHINGBOATSCOLORSOFTHERAINBOW')
df = df[['First Line', 'Second Line', 'Third Line']]

# Check the cleaned dataframe to make sure everything is correct
print(df.head())

# Step 6: Prepare the Dataset (Text Preprocessing)
# Ensure all columns are strings before concatenating
df['First Line'] = df['First Line'].fillna('').astype(str)
df['Second Line'] = df['Second Line'].fillna('').astype(str)
df['Third Line'] = df['Third Line'].fillna('').astype(str)

# Combine the 'First Line', 'Second Line', and 'Third Line' to create a full haiku for each row
poems = df['First Line'] + "\n" + df['Second Line'] + "\n" + df['Third Line']

# Clean the text by stripping whitespace and removing any empty haikus
poems = poems[poems.str.strip().apply(lambda x: len(x) > 0)].tolist()

# Join all the haikus into one large string, separated by new lines
poems_text = "\n".join(poems)

# Check the first few poems to ensure it's working
print(poems[:25])

# Step 7: Prepare the Dataset for Fine-Tuning (Formatting Prompts)
# Define prompt format for model training
alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{}

### Input:
{}

### Response:
{}"""

from transformers import AutoTokenizer #type: ignore

#tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-1B-Instruct")

# Formatting function for haiku dataset
EOS_TOKEN = tokenizer.eos_token  # Must add EOS_TOKEN
def formatting_prompts_func(examples):
    instructions = examples["First Line"]
    inputs = examples["Second Line"]
    outputs = examples["Third Line"]
    texts = []
    for instr, inp, out in zip(instructions, inputs, outputs):
        # Add EOS_TOKEN to end of each prompt
        text = alpaca_prompt.format(instr, inp, out) + EOS_TOKEN
        texts.append(text)
    return {"text": texts}

# Apply the formatting to the dataset
from datasets import Dataset #type: ignore
from datasets import load_dataset

# Ensure all values are strings and replace NaN with empty strings
df['First Line'] = df['First Line'].fillna('').astype(str)
df['Second Line'] = df['Second Line'].fillna('').astype(str)
df['Third Line'] = df['Third Line'].fillna('').astype(str)

# Create a dataset from the haiku text, ensuring all values are strings
dataset = Dataset.from_dict({
    "First Line": df['First Line'],
    "Second Line": df['Second Line'],
    "Third Line": df['Third Line'],
})

# Map the formatting function to the dataset

dataset = dataset.map(formatting_prompts_func, batched=True)
print(dataset[0])
print(f"Number of examples: {len(dataset)}")

# Now the dataset is ready for fine-tuning

import os
import torch
import gc
from unsloth import FastLanguageModel #type: ignore
from trl import SFTTrainer #type: ignore
from transformers import TrainingArguments
from peft import get_peft_model, LoraConfig, TaskType
from accelerate import Accelerator

from trl import GRPOConfig, GRPOTrainer #type: ignore

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    packing = False, # Can make training 5x faster for short sequences.
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5, #maybe change to 50 for smoother start
        num_train_epochs = 1, # Set this for 1 full training run.
        max_steps = 60,  #add more steps for better training
        learning_rate = 2e-4,  #maybe change to 1e-4 for finer updates
        fp16 = not is_bfloat16_supported(),
        bf16 = is_bfloat16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear", #maybe change to cosine for better training
        seed = 3407,
        output_dir = "outputs",
        report_to = "none", # Use this for WandB etc
    ),
)
trainer_stats = trainer.train() #type: ignore

# alpaca_prompt = Copied from above
FastLanguageModel.for_inference(model) # Enable native 2x faster inference
inputs = tokenizer(
[
    alpaca_prompt.format(
        "Give me a beautiful, long haiku about nature", # instruction
        "", # input
        "", # output - leave this blank for generation!
    )
], return_tensors = "pt").to("cuda")

outputs = model.generate(**inputs, max_new_tokens = 64, use_cache = True)
tokenizer.batch_decode(outputs)